common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from watcha.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('netplix/', include('watcha.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
]

watcha/urls.py
from django.urls import path

from .views import base_views, movie_views, recommend_views

app_name = 'watcha'

urlpatterns = [
    # base_views.py
    path('',
         base_views.index, name='index'),
    path('movie/vote/<int:movie_id>/', movie_views.movie_vote, name='movie_vote'),
    path('recommend/', recommend_views.movie_display, name='recommend'),

    # # question_views.py
    # path('question/create/',
    #      question_views.question_create, name='question_create'),
    # path('question/modify/<int:question_id>/',
    #      question_views.question_modify, name='question_modify'),
    # path('question/delete/<int:question_id>/',
    #      question_views.question_delete, name='question_delete'),
    #
    # # answer_views.py
    # path('answer/create/<int:question_id>/',
    #      answer_views.answer_create, name='answer_create'),
    # path('answer/modify/<int:answer_id>/',
    #      answer_views.answer_modify, name='answer_modify'),
    # path('answer/delete/<int:answer_id>/',
    #      answer_views.answer_delete, name='answer_delete'),
    ]

common/models.py
from django.db import models

# Create your models here.

watcha/models.py
from django.db import models
from django.contrib.auth.models import User


class Movie(models.Model):
    title = models.CharField(max_length=200)
    story = models.TextField()
    url = models.CharField(max_length=200)
    order = models.IntegerField(default=-1)
    voter = models.ManyToManyField(User, related_name='voter_movie')  # 추천인 추가
    def __str__(self):
        return self.title

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def signup(request):

    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html',    {'form': form})

watcha/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from ..models import Movie
import pandas as pd

# data = pd.read_csv('./resources/data.csv', encoding='cp949')
# for i in range(len(data)):
#    m = Movie()
#    m.title = data['title'][i]
#    m.story = data['story'][i]
#    m.url = data['url'][i]
#    m.save()

def index(request):
    movie_list = Movie.objects.order_by('title')
    context = {'movie_list': movie_list}
    return render(request, 'watcha/movie_list.html', context)

watcha/views/movie_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url

from ..models import Movie


@login_required(login_url='common:login')
def movie_vote(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    movie.voter.add(request.user)
    return redirect('{}#movie_{}'.format(resolve_url('watcha:index'), movie.id))

watcha/views/recommend_views.py
import itertools

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.db.models import Q

from ..models import Movie

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

data = pd.read_csv('/home/hdydtdxdt/NETPLIX/resources/data.csv', encoding='cp949')
first = int(len(data) / 3)
second = int(len(data) / 3 * 2)
third = int(len(data))
stopwords = []
stopwords_path = '/home/hdydtdxdt/NETPLIX/resources/stopwords.txt'

with open(stopwords_path, 'r', encoding='utf-8') as stopwords_file:
    line = stopwords_file.readline()

    while True:
        line = stopwords_file.readline()
        if not line: break
        stopwords.append(line[:-1])

stopwords_file.close()

tfidf = TfidfVectorizer(stop_words=stopwords)
tfidf_matrix = tfidf.fit_transform(data['story'])

cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

def reset_order():
    movies = Movie.objects.all()
    for movie in movies:
        movie.order = -1
        movie.save()

def get_recommendations(title, cosine_sim=cosine_sim):
    title_to_index = dict(zip(data['title'], data.index))
    idx = title_to_index[title]

    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    similar_movie_scores = sim_scores[:first]
    similar_movie_indices = [idx[0] for idx in similar_movie_scores]

    return similar_movie_indices

def evaluate(request):
    user_movies = data.copy()
    for i in range(len(user_movies)):
        user_movies['score'] = 0

    reset_order()

    sorted_movies = []
    similar_movies = []
    opposite_movies = []

    titles = []

    user = request.user
    voted_movies = user.voter_movie.all()

    if len(voted_movies) == 0:
        return 0
    else:
        for i in range(len(voted_movies)):
            indexes = get_recommendations(voted_movies[i].title)
            for index in indexes:
                user_movies.loc[index, 'score'] += 10

        user_movies = user_movies.sort_values(by='score', ascending=False)
        user_movies = user_movies.reset_index(drop=True)

        for i in range(len(user_movies)):
            titles.append(user_movies.loc[i, 'title'])

        for i in range(second):
            similar_movies.append(titles[i])

        for i in range(second, third):
            opposite_movies.append(titles[i])

        j = 0
        k = 0
        while True:
            if j == 184:
                break
            sorted_movies.append(similar_movies[j:j + 8])
            sorted_movies.append(opposite_movies[k:k + 8])
            j += 8
            k += 2
        sorted_movies.append(similar_movies[j:186])
        sorted_movies.append(opposite_movies[k:k + 2])

        sorted_movies = list(itertools.chain(*sorted_movies))

        order = 1
        for sorted_title in sorted_movies:
            movies = Movie.objects.filter(title=sorted_title)
            for movie in movies:
                movie.order = order
                movie.save()
            order += 1

@login_required(login_url='common:login')
def movie_display(request):
    evaluate(request)
    movie_list = Movie.objects.filter(~Q(order=-1))
    movie_list = movie_list.order_by('order')
    context = {'movie_list': movie_list}
    return render(request, 'watcha/movie_recommend.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/png">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/png">
    <title>NETPLIX</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 End -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

templates/form_errors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light border-bottom">
    <div class="container-fluid navbar-custom">
        <a class="navbar-brand ms-4" href="{% url 'watcha:index' %}"><img src="../../static/logo.png" style="width:36px; height:65px;"></a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item ms-3">
                    {% if user.is_authenticated %}
                    <a class="nav-link nav-menu" href="{% url 'watcha:recommend' %}">추천 피드</a>
                    {% endif %}
                </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/watcha/movie_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h1 class="subtitle mt-4 mb-5">탐색하기</h1>
    {% for movie in movie_list %}
    <a id="movie_{{ movie.id }}"></a>
        <h2 class="border-bottom py-2 movie-title">{{ movie.title }}</h2>
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line;">{{ movie.story }}</div>
                <div class="mt-5">
                    <a href="{% url 'watcha:movie_vote' movie.id  %}" class="recommend btn btn-sm like-button">Like
                        <span class="badge rounded-pill like-number-span">{{movie.voter.count}}</span>
                    </a>
                    <a href="{{ movie.url}} " class="btn btn-sm preview-button float-end">예고편</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock%}

templates/watcha/movie_recommend.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h1 class="subtitle mt-4 mb-5">추천 피드</h1>
    {% for movie in movie_list %}
    <a id="movie_{{ movie.id }}"></a>
        <h2 class="border-bottom py-2 movie-title">{{ movie.title }}</h2>
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line;">{{ movie.story }}</div>
                <div class="mt-5">
                    <a href="{{ movie.url}} " class="btn btn-sm preview-button float-end">예고편</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock%}